# Generated by Django 5.0.1 on 2024-01-27 03:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='choice',
            old_name='questio',
            new_name='question',
        ),
    ]
